Feature/initialize my portfolio
MahdiAghaali/My-Portfolio pull request #1
Opened 2022-08-17 15:34 UTC by MahdiAghaali

In this Milestone I... 

- [ ] Initialize my project correctly and set up Linters.

and 

- Try to understand how to parse a Figma design to create a UI.
- Use flexbox to place elements on the page.
- Build a personal portfolio site.
- Use images and backgrounds to enhance the look of the website.

2022-08-17 20:48 UTC, topeogunleye requested changes
Hi @MahdiAghaali, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your @topeogunleye so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 20:48 UTC, topeogunleye commented on Index.html
> +    <img
- [ ] I kindly suggest that you surround you hamburger menu with a nav tag because it is a navigation element and for semantic reasons.

2022-08-17 20:48 UTC, topeogunleye commented on Index.html
> +    <header>
- [ ] I kindly suggest that you ensure your hamburger menu and logo are aligned horizontally with a space in between just as seen in the Figma design.
- The nav bar is on the right for convention and user experience for mobile devices.

| Your Design  | Figma Design |
| ------------- | ------------- |
|<img width="317" alt="fffffff" src="https://user-images.githubusercontent.com/52934128/185234709-b23da57c-cc74-4532-b943-0410f8d93bbb.PNG">  | <img width="256" alt="ffff" src="https://user-images.githubusercontent.com/52934128/185234825-f9c4b316-2971-4be1-92f0-1e942e7edcb8.PNG">  |

2022-08-17 20:48 UTC, topeogunleye commented on Index.html
> +    <img
- [ ] Kindly ensure that if the image is not part of the content (aesthetic reasons), use CSS background-image. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.

2022-08-17 20:48 UTC, topeogunleye commented on Index.html
> +      <h1>Hi, I'm <b>Mahdi Aghaali</b>, Happy to see you</h1>
- [ ] I kindly suggest that you make use of the right font color for your `header` and `paragraph`. The color for your `header` and `paragraph from the Figma design is `#1A2236;`

2022-08-17 20:48 UTC, topeogunleye commented on Index.html
> +      <button type="button" id="btn-collaboration">Start collaboration</button>
![image](https://user-images.githubusercontent.com/52934128/185237344-c0bf8ed5-d355-41d8-9f3a-0cbe44bfa3c4.png)

- [ ] I kindly suggest that you add the different button interactions including hover, active (when it's pressed), disabled, and enable (default state) as shown in the Figma template below:

![image](https://user-images.githubusercontent.com/52934128/185237857-8c70c3b2-d3de-433f-911c-283ab0cc23dd.png)

the button on pressed state has `background: #E5E5E5;` the button on the normal state has the `background: #1A2236;` and on hover has the `background: #E5E5E5;`

### EXAMPLE:
**for pressed state**
```
button:active {
   background-color: #E5E5E5;
}
```
**for hover state**
```
button:hover {
    background-color: #E5E5E5;
}
```

- [ ] I kindly suggest that you follow the Figma design for creating your button. please follow the padding, margin, font colors in the design.
- [ ] I kindly suggest that you ensure the button is centered just like it is in the design template

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/52934128/185240061-eef42822-b1e7-41a2-a502-d4347294f9db.png)  | ![image](https://user-images.githubusercontent.com/52934128/185239880-b6251ad7-23e7-4c3b-a44a-9272edbc9825.png)  |

2022-08-18 14:49 UTC, MahdiAghaali commented
![dsadsads](https://user-images.githubusercontent.com/93377744/185425070-579c79e8-6f47-4885-a952-470f3c2c3482.JPG)

2022-08-18 15:07 UTC, danmainah requested changes
Hi @MahdiAghaali , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 15:07 UTC, danmainah commented on index.css
> +button:hover {
- [ ] Kindy check on your hover functionality it doesn't work when I test it. You can use [this guide ](https://html.form.guide/web-form-widget/css3-button-hover-effects/)

2022-08-18 16:08 UTC, MahdiAghaali commented on index.css
> +button:hover {
Maybe because there is no hover functionality in mobile mode?
if you want to check hover you have to check it in the PC version.
![Hover](https://user-images.githubusercontent.com/93377744/185442562-54dda328-6d87-419e-ac28-8665e5fe23c1.gif)

2022-08-18 16:16 UTC, danmainah commented on index.css
> +button:hover {
@MahdiAghaali let me recheck it I did it on the desktop view

2022-08-18 16:22 UTC, danmainah commented on index.css
> +button:hover {
@MahdiAghaali its working I will approve it and make sure to forward the issue so as it can reflect in the dashboard

2022-08-18 16:36 UTC, merged